spring:
  profiles:
    active: local
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /pt
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /api-docs
    resolveSchemaProperties: true

api:
  cdp:
    client_id: 894018941704-2gn88c8qugmjhcar020usr9cr6vqft2q.apps.googleusercontent.com
  googleSpreadSheets:
    url: https://sheets.googleapis.com