spring:
  config:
    activate:
      on-profile: dev
  datasource:
    master:
      jdbc-url: jdbc:postgresql://rds-cdp-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
      username: cdpdevdb_app
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-master
    slave:
      jdbc-url: jdbc:postgresql://rds-cdp-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
      username: cdpdevdb_app
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-slave
    oneid:
      jdbc-url: jdbc:postgresql://oneiddb-dev.koreanair.com:5957/oneiddevdb?charSet=UTF-8
      username: oneiddevdb_app
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-oneid
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'
  devtools:
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
  redis:
    host: redis-oneid-dev.koreanair.com
    port: 6980
    #session-ttl: 1200
    session-ttl: 32400
    
logging:
  level:
    root: info
    org:
      springframework: debug
    com:
      cdp:
        portal: debug
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread]%cyan( %logger{10}) - %msg%n"
      
cloud:
  aws:
    region: ap-northeast-2
    secrets-manager:
      db-password-arn: arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:rds/dlk/dev/cdp/app-Yufwll
      db-password-arn-oneid: arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:rds/dlk/dev/oneid/oneiddevdb-X6cSCC

hr:
  arn: arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:secret/dlk/dev/cdp-UzdVxY

# AWS Properties
aws-props:
  bucket-name: awsdc-s3-dlk-dev-cdp-portalobject
  s3-uri : s3://awsdc-s3-dlk-dev-cdp-portalobject
  file-path: "board"
  page-size: "10"
  time-zone: "Asia/Seoul"
      
      