spring:
  profiles:
    active: local
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
      
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /api-docs
    resolveSchemaProperties: true
  