spring:
  config:
    activate:
      on-profile: local
  datasource:
    master:
      jdbc-url: jdbc:log4jdbc:postgresql://rds-cdp-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
      username: cdpdevdb_mgr
      password: h@#Ru0Ro
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-master
    slave:
      jdbc-url: jdbc:postgresql://rds-cdp-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
      username: cdpdevdb_user
      password: G$BRl5$B
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-slave
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  redis:
    host: redis-oneid-dev.koreanair.com
    port: 6980
    session-ttl: 1200

logging:
  level:
    root: info
    org:
      springframework: debug
    com:
      cdp:
        portal:
          app: debug
      zaxxer:
        hikari: off
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: error
      resultsettable: info
      connection: off
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread]%cyan( %logger{10}) - %msg%n"

cloud:
  aws:
    region: ap-northeast-2
    role:
      arn: arn:aws:iam::658379516860:role/CDP-PORTALDEVELOPER
    secrets-manager:
      db-password-arn: arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:rds/dlk/dev/cdp/app-Yufwll
      s3:
        bucket: "awsdc-s3-dlk-dev-cdp-portalobject"
      credentials:
    accessKey: ASIAZSST2FO6D5V6Q6FU
    secretKey: 1/4ACdh4Ed1mfPQw3k70bXWcPjmWUXCVB/CA95Ao


# AWS Properties
aws-props:
  bucket-name: awsdc-s3-dlk-dev-cdp-portalobject
  s3-uri : s3://awsdc-s3-dlk-dev-cdp-portalobject
  file-path: "board"
  page-size: "10"
  time-zone: "Asia/Seoul"