spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://cdpdb-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
    driver-class-name: org.postgresql.Driver
    username: cdpdevdb_app
    password: efR-as0o
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'
  devtools:
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
      
mybatis:
  type-aliases-package: com.cdp.portal
  type-handlers-package: com.cdp.portal
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: NULL
    use-generated-keys: false
  mapper-locations: classpath:mapper/**/*.xml
    
logging:
  level:
    root: info
    org:
      springframework: debug
    com:
      cdp:
        portal: debug
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread]%cyan( %logger{10}) - %msg%n"
      
    