spring:
  config:
    activate:
      on-profile: dev
  datasource:
    master:
      jdbc-url: jdbc:postgresql://rds-cdp-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
      username: cdpdevdb_app
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-master
    slave:
      jdbc-url: jdbc:postgresql://rds-cdp-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
      username: cdpdevdb_app
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-slave
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'
  devtools:
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
  redis:
    host: redis-oneid-dev.koreanair.com
    port: 6980
    session-ttl: 1200
    
logging:
  level:
    root: info
    org:
      springframework: debug
    com:
      cdp:
        portal: debug
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread]%cyan( %logger{10}) - %msg%n"
      
cloud:
  aws:
    region: ap-northeast-2
    secrets-manager:
      db-password-arn: arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:rds/dlk/dev/cdp/app-Yufwll
      
      