spring:
  profiles:
    active: local

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /pt
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  type-aliases-package: com.cdp.portal
  type-handlers-package: com.cdp.portal
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: NULL
    use-generated-keys: false
  mapper-locations: classpath:mapper/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /api-docs
    resolveSchemaProperties: true

api:
  cdp:
    client_id: 894018941704-2gn88c8qugmjhcar020usr9cr6vqft2q.apps.googleusercontent.com
  googleSpreadSheets:
    url: https://sheets.googleapis.com

cloud:
  aws:
    s3:
      bucket: awsdc-s3-dlk-dev-cdp-portalobject
  stack.auto: false
  region.static: ap-northeast-2
  credentials:
    accessKey: ASIAZSST2FO6CY7LWGDJ
    secretKey: ot20S5tIRroxNWcGEvy9zj+7i2z2LObZDTdVoyT+

local:
  database:
    password:
      master-password: h@#Ru0Ro
      slave-password: G$BRl5$B