spring:
  config:
    activate:
      on-profile: local
  datasource:
    master:
      jdbc-url: jdbc:log4jdbc:postgresql://rds-cdp-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
      username: cdpdevdb_mgr
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-master
    slave:
      jdbc-url: jdbc:log4jdbc:postgresql://rds-cdp-dev.koreanair.com:5957/cdpdevdb?currentSchema=cdp
      username: cdpdevdb_user
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-slave
    oneid:
      jdbc-url: jdbc:log4jdbc:postgresql://oneiddb-dev.koreanair.com:5957/oneiddevdb?charSet=UTF-8
      username: oneiddevdb_app
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 10000
        pool-name: cdp-oneid
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  redis:
    host: redis-oneid-dev.koreanair.com
    port: 6980
    session-ttl: 1200

logging:
  level:
    root: info
    org:
      springframework: debug
    com:
      cdp:
        portal: debug
      zaxxer:
        hikari: off
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: error
      resultsettable: info
      connection: off
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread]%cyan( %logger{10}) - %msg%n"

cloud:
  aws:
    region: ap-northeast-2
    role:
      arn: arn:aws:iam::658379516860:role/CDP-PORTALDEVELOPER
    secrets-manager:
      db-password-arn: arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:rds/dlk/dev/cdp/app-Yufwll
      db-password-arn-oneid: arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:rds/dlk/dev/oneid/oneiddevdb-X6cSCC
      s3:
        bucket: "awsdc-s3-dlk-dev-cdp-portalobject"
      credentials:
    accessKey: ASIAZSST2FO6D5V6Q6FU
    secretKey: 1/4ACdh4Ed1mfPQw3k70bXWcPjmWUXCVB/CA95Ao

hr:
  arn: arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:secret/dlk/dev/cdp-UzdVxY

# AWS Properties
aws-props:
  bucket-name: awsdc-s3-dlk-dev-cdp-portalobject
  s3-uri : s3://awsdc-s3-dlk-dev-cdp-portalobject
  file-path: "board"
  page-size: "10"
  time-zone: "Asia/Seoul"
  
core:
  aws:
    role-switching:
      enable: false
    kms:
      encrypt:
        aes:
          keyId: "arn:aws:kms:ap-northeast-2:993398491107:key/mrk-e7bc670f9a6c46f884d0fee2cc12017c"
        sha:
          keyId: "arn:aws:kms:ap-northeast-2:993398491107:key/mrk-0b9e9afc2c6a4f7dab63a94a470bc986"
    secretsmanager:
      oneid:
        arn: "arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:rds/dlk/dev/oneid/oneiddevdb-X6cSCC"
        region: ap-northeast-2
        enabled: true
      cdp:
        arn: "arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:rds/dlk/dev/cdp/cdpdevdb-VDgFOR"
        region: ap-northeast-2
        enabled: true
        
external:
  cdp-api:
    url: http://localhost:8082/api/